### ISSUE TITLE
Expose the eat function

### ISSUE THREAD

**Issue by imharvol** [LINKdiscordd/mineflayer-auto-eat#2]
In some bots the plugin can't be used because the bot might try to eat while doing some other thing (breaking blocks, ...) thus interfering. But [the eat function](https://github.com/LINKdiscordd/mineflayer-auto-eat/blob/0a0acb5b226912ac8d9915cd87d89fa66dda1c05/index.js#L24-L79) is really useful and I think it would be nice to expose it, that would allow the user to decide when to eat so it doesn't interfere.

It would require a callback to know when the bot is done eating.

**Comment by LINKdiscordd** [comment]
Thanks for the feedback!

I will defenitly implement this

**Comment by LINKdiscordd** [comment]
well, I'm kinda 9 days late but whatever, definitely gonna implement it today
I had some school stuff

**Comment by LINKdiscordd** [comment]
Done and the package has been updated to 1.3.0
