### ISSUE TITLE
Does not work :(

### ISSUE THREAD

**Issue by DrMoraschi** [LINKdiscordd/mineflayer-auto-eat#3]
Package is completely broken, bot doesn't eat. Even with the example it just stays there

**Comment by LINKdiscordd** [comment]
Idk how that is possible but ig I will try the example code myself and see

**Comment by LINKdiscordd** [comment]
I didn't have any errors

**Comment by LINKdiscordd** [comment]
also it worked fine for me when I tested it so I don't know what the issue is

maybe you can show me some errors if you have any

**Comment by DrMoraschi** [comment]
https://imgur.com/a/wPwE837

Using the example

**Comment by LINKdiscordd** [comment]
I don't see where the issue is
the bot doesn't eat when its low on health
only when low on hunger

**Comment by DrMoraschi** [comment]
On the example script, if bot.food is equal to 20(full) it disables the plugin. But if else, it enables it. When regenerating health, food decreases, so it should activate the plugin.

**Comment by DrMoraschi** [comment]
Never mind I'm stupid, I didn't look at the startAt option

**Comment by DrMoraschi** [comment]
`E:\[bot folder]\node_modules\mineflayer-auto-eat\index.js:90
                        callback(null)
                        ^

TypeError: callback is not a function
    at Immediate.<anonymous> (E:\Node Bots\Temp\node_modules\mineflayer-auto-eat\index.js:90:25)
    at processImmediate (internal/timers.js:458:21`

**Comment by LINKdiscordd** [comment]
oh yeah I can fix that

**Comment by DrMoraschi** [comment]
Thx

**Comment by LINKdiscordd** [comment]
it requires a callback but I forgot to change my code to use the callback as well

**Comment by OctodevGITHUB** [comment]
I am now having this same error. My alt just stays there and doesn't eat and in the terminal it says "Auto eat enabled" and then immediately says "Auto eat disabled". This is my code. https://pastebin.com/kNHfYY1e

**Comment by link-discord** [comment]
Will look into it later today
